quarkus.rest-client.profiel-service.url=http://profiel-service
%dev.quarkus.rest-client.profiel-service.url=http://localhost:8081
%test.quarkus.rest-client.profiel-service.url=http://localhost:8081

quarkus.rest-client.notify.url=https://notifynl.example.invalid
notify.api-key=
notify.template-id=

mp.openapi.scan.disable=true
