-- V4: statusmodel, pogingen en eventlog uit ADR 0024, naast het bestaande model. Nog niets schrijft
-- hierin behalve Overgangsfunctie; de databasetrigger en het vullen uit notificatie_status volgen
-- samen met de overstap van het schrijfpad.

ALTER TABLE notificatie ADD COLUMN status varchar(32) CHECK (status IN (
    'AANGENOMEN', 'IN_VERZENDING', 'VERZONDEN', 'BEZORGD', 'DEFINITIEF_BEZORGD', 'NIET_BEZORGBAAR',
    'TECHNISCH_MISLUKT', 'BEZORGSTATUS_ONBEKEND', 'VERLOPEN', 'GEANNULEERD'
));
ALTER TABLE notificatie ADD COLUMN reden varchar(32) CHECK (reden IN (
    'ONBEREIKBAAR', 'GEEN_CONTACTGEGEVENS', 'VERLOPEN', 'GEANNULEERD', 'TECHNISCH'
));

CREATE TABLE poging (
    id uuid PRIMARY KEY,
    notificatie_id uuid NOT NULL REFERENCES notificatie(id) ON DELETE CASCADE,
    nummer integer NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN (
        'GEPLAND', 'VERZONDEN', 'BEZORGD', 'TIJDELIJK_MISLUKT', 'PERMANENT_MISLUKT', 'TECHNISCH_MISLUKT', 'ONBEKEND'
    )),
    notify_id uuid UNIQUE,
    duplicaat_ids uuid[] NOT NULL DEFAULT '{}',
    verzonden_op timestamp(6) with time zone,
    receipt_tijdstip timestamp(6) with time zone,
    UNIQUE (notificatie_id, nummer)
);

-- xid is de transactie-id van de schrijvende transactie; de feed leest op (xid, id) onder het
-- watermerk van de oudste lopende transactie. Gepartitioneerd op xid, zodat opruimen per partitie
-- kan; de primary key moet daarom xid bevatten. Geen foreign key naar notificatie: het log wordt
-- per partitie opgeruimd, los van de notificatierijen.
CREATE TABLE event (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    xid xid8 NOT NULL DEFAULT pg_current_xact_id(),
    tijdstip timestamp(6) with time zone NOT NULL,
    notificatie_id uuid NOT NULL,
    volgnummer bigint NOT NULL,
    van varchar(32),
    naar varchar(32) NOT NULL,
    reden varchar(32),
    PRIMARY KEY (xid, id)
) PARTITION BY RANGE (xid);

-- Vangt alles op zolang er geen bereikpartities zijn; die maakt de onderhoudstaak aan.
CREATE TABLE event_standaard PARTITION OF event DEFAULT;

CREATE INDEX event_notificatie_volgnummer_idx ON event (notificatie_id, volgnummer);

-- De toegestane statusovergangen; gelijk aan Overgangsregels, bewaakt door een test.
CREATE TABLE toegestane_overgang (
    van varchar(32) NOT NULL,
    naar varchar(32) NOT NULL,
    PRIMARY KEY (van, naar)
);

INSERT INTO toegestane_overgang (van, naar) VALUES
    ('AANGENOMEN', 'IN_VERZENDING'),
    ('AANGENOMEN', 'VERLOPEN'),
    ('AANGENOMEN', 'GEANNULEERD'),
    ('IN_VERZENDING', 'VERZONDEN'),
    ('IN_VERZENDING', 'TECHNISCH_MISLUKT'),
    ('IN_VERZENDING', 'VERLOPEN'),
    ('IN_VERZENDING', 'NIET_BEZORGBAAR'),
    ('VERZONDEN', 'VERZONDEN'),
    ('VERZONDEN', 'VERLOPEN'),
    ('VERZONDEN', 'BEZORGD'),
    ('VERZONDEN', 'NIET_BEZORGBAAR'),
    ('VERZONDEN', 'TECHNISCH_MISLUKT'),
    ('VERZONDEN', 'BEZORGSTATUS_ONBEKEND'),
    ('BEZORGSTATUS_ONBEKEND', 'BEZORGD'),
    ('BEZORGSTATUS_ONBEKEND', 'NIET_BEZORGBAAR'),
    ('BEZORGD', 'DEFINITIEF_BEZORGD'),
    ('BEZORGD', 'VERZONDEN'),
    ('BEZORGD', 'NIET_BEZORGBAAR'),
    ('BEZORGD', 'VERLOPEN');
