-- V8: dienstverlener, takentabel en verzendbudget uit ADR 0024. Tot de tokenvalidatie per
-- dienstverlener er is, is er één geconfigureerde dienstverlener; notificatie en event dragen zijn
-- dv_id, zodat claim, sleutel en feed er nu al op werken.

CREATE TABLE dienstverlener (
    id uuid PRIMARY KEY,
    oin varchar(20) NOT NULL UNIQUE,
    naam varchar(200) NOT NULL
);

-- Vaste id, gelijk aan de default van nmc.dienstverlener.id. Het OIN is een placeholder tot de
-- onboarding het echte levert.
INSERT INTO dienstverlener (id, oin, naam)
VALUES ('00000000-0000-4000-8000-000000000001', '00000000000000000000', 'Geconfigureerde dienstverlener');

ALTER TABLE notificatie ADD COLUMN dv_id uuid REFERENCES dienstverlener(id);
-- De update zet deferred triggercontroles klaar (zelfde versie en status, dus die slagen), en zolang die
-- openstaan weigert PostgreSQL DDL op notificatie.
SET CONSTRAINTS notificatie_overgang IMMEDIATE;
UPDATE notificatie SET dv_id = '00000000-0000-4000-8000-000000000001' WHERE dv_id IS NULL;
ALTER TABLE notificatie ALTER COLUMN dv_id SET NOT NULL;

-- Geen foreign key: het log wordt per partitie opgeruimd, los van de andere tabellen.
ALTER TABLE event ADD COLUMN dv_id uuid;
UPDATE event SET dv_id = '00000000-0000-4000-8000-000000000001' WHERE dv_id IS NULL;
ALTER TABLE event ALTER COLUMN dv_id SET NOT NULL;

-- Bijwerkingen als geleasede taken; timers zijn due-tijdstippen. Gepartitioneerd op soort, zodat
-- een soort met veel rijen de claim op de andere soorten niet vertraagt en rijen per soort zijn op
-- te ruimen; de primary key moet daarom soort bevatten. dv_id is leeg voor taken per systeem.
CREATE TABLE taak (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    soort varchar(32) NOT NULL CHECK (soort IN (
        'VERZENDEN', 'RECEIPT_VERWERKEN', 'RECONCILIEREN', 'BEZORGING_VASTSTELLEN', 'TERUGKOPPELEN',
        'ONGELDIG_MELDEN', 'WISSEN', 'CONTROLE', 'ONDERHOUD'
    )),
    dv_id uuid REFERENCES dienstverlener(id),
    notificatie_id uuid REFERENCES notificatie(id) ON DELETE CASCADE,
    due timestamp(6) with time zone NOT NULL,
    lease_tot timestamp(6) with time zone,
    claim_epoch bigint NOT NULL DEFAULT 0,
    pogingen integer NOT NULL DEFAULT 0,
    trace_id varchar(64),
    status varchar(16) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'MISLUKT')),
    payload jsonb,
    PRIMARY KEY (soort, id)
) PARTITION BY LIST (soort);

CREATE TABLE taak_verzenden PARTITION OF taak FOR VALUES IN ('VERZENDEN');
CREATE TABLE taak_receipt_verwerken PARTITION OF taak FOR VALUES IN ('RECEIPT_VERWERKEN');
CREATE TABLE taak_reconcilieren PARTITION OF taak FOR VALUES IN ('RECONCILIEREN');
CREATE TABLE taak_bezorging_vaststellen PARTITION OF taak FOR VALUES IN ('BEZORGING_VASTSTELLEN');
CREATE TABLE taak_terugkoppelen PARTITION OF taak FOR VALUES IN ('TERUGKOPPELEN');
CREATE TABLE taak_ongeldig_melden PARTITION OF taak FOR VALUES IN ('ONGELDIG_MELDEN');
CREATE TABLE taak_wissen PARTITION OF taak FOR VALUES IN ('WISSEN');
CREATE TABLE taak_controle PARTITION OF taak FOR VALUES IN ('CONTROLE');
CREATE TABLE taak_onderhoud PARTITION OF taak FOR VALUES IN ('ONDERHOUD');

-- Per notificatie hoogstens één open taak per soort; receipttaken vallen hier later buiten.
CREATE UNIQUE INDEX taak_open_per_notificatie_idx ON taak (notificatie_id, soort)
    WHERE status = 'OPEN' AND notificatie_id IS NOT NULL;

-- De claim leest op soort, dienstverlener en due, alleen open taken.
CREATE INDEX taak_claim_idx ON taak (soort, dv_id, due) WHERE status = 'OPEN';

-- Tokens per Notify-service per tijdvak van een minuut; de eerste claim in een tijdvak maakt de
-- rij aan. Niet-gebruikte tokens vervallen met het tijdvak.
CREATE TABLE verzendbudget (
    notify_service varchar(64) NOT NULL,
    tijdvak timestamp(6) with time zone NOT NULL,
    tokens integer NOT NULL CHECK (tokens >= 0),
    PRIMARY KEY (notify_service, tijdvak)
);
